CREATE DATABASE DB_BITFLY;
USE DB_BITFLY;

CREATE TABLE TB_USUARIO(
	codigo INT PRIMARY KEY AUTO_INCREMENT,
	usuario VARCHAR(200),
    email VARCHAR(200),
    senha VARCHAR(200)
);

CREATE TABLE TB_EVENTOS(
	codigo INT PRIMARY KEY AUTO_INCREMENT,
    empresa VARCHAR(200),
    dia VARCHAR (200),
    horario VARCHAR (200),
    lugar VARCHAR (200),
    cnpj VARCHAR (200)
);

SELECT * FROM TB_USUARIO;
SELECT * FROM TB_EVENTOS;

INSERT INTO TB_USUARIO (usuario, email, senha) VALUES ();
INSERT INTO TB_EVENTOS(empresa, dia, horario, lugar, cnpj) VALUES ();


SET GLOBAL time_zone = '-3:00'